<a href="https://colab.research.google.com/github/jugernaut/Numerico2021/blob/master/00_Introduccion/03_CCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Complejidad, Convergencia y Crecimiento del error.</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C. Miguel Angel Pérez León.</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón.</i></h5>
  <h5 align="center"><i>Materia: Análisis Numérico.</i></h5>
  </font>

## Introducción 

En presentaciones pasadas sentamos las bases de lo que es el análisis numérico. Y se mostráron algunas definiciones que sirven para realizar el análisis de un algoritmo.

Podemos pensar en estas definiciones como las herramientas de un médico que quiere examinar a un pasciente, en este caso un algoritmo.

Dichas herramientas son:

1.   Complejidad Computacional (cota superior asintótica).
2.   Convergencia.
3.   Crecimiento del error.

Para mostrar de manera práctia como emplear estas herramientas vamos a ver un par de ejemplos y de como llevar a cabo el análisis de dichos algoritmos.

## Matrices

Es bien conocido que las matrices son un elemento fundamental en el contexto matemático y por lo tanto es de vital importancia analizar los algoritmos que modelan el funcionamiento teórico de estos elementos.

Por otra parte los algoritmos asociados a las operaciones en el subespacio de las matrices son candidatos ideales para realizar su analisis.

Para simplificar un poco los ejemplos, vamos a restringir un poco el alcance de estos algoritmos al subespacio de las matrices cuadradas sobre el campo de los reales, es decir $A\in M_{n\times n}$ sobre $\mathbb{R}$. Sin embargo muchos de estos algoritmos se pueden extender al subespacio de las matrices de $m \times n$ incluso en campo de los números complejos.


### Creación de una matriz

Para facilitar la definición de nuestros algoritmos vamos a usar la paqueteria numpy de python, esta paqueteria es la encargada de facilitar muchos de los cálculos que realizaremos en el semestre.

Sin embargo, podemos pensar que una matriz es una lista de listas (viendolo desde el punto de vista de la computación) o incluso un vector de vectores.

In [6]:
import numpy as np

#crea una matriz de tam x tam con unos y la imprime    
def creaMatriz(tam):
    #crea una matriz de tam x tam
    a = np.ones((tam,tam))
    #se devuelve la matriz 
    return a

# se imprime la matriz
print(creaMatriz(4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Este algoritmo unicamente sirve para generar una matriz de tamaño $n \times n$ en la que todas sus entradas tienen el valor 1, es decir.

$$A=\left(\begin{array}{ccc}
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1
\end{array}\right)$$

A partir de este punto podemos acceder a los elementos de la matriz mediante la notacion *a[i][j]* donde i,j pertenecen a los indices de los renglones y las columnas respectivamente $a_{i,j}\;\forall\,i,j=0,\ldots,n-1$

### Traza de una matriz

El cálculo de la traza de una matriz es una de las operaciones mas sencillas de realizar, siempre y cuando se realice de manera correcta y se define como la suma de los elementos en la diagonal de la matriz.

Sea $A\in M_{n\times n}$ sobre $\mathbb{R}$ la traza de A se define como sigue.

$$traza(A)=a_{0,0}+a_{1,1}+\cdots a_{n-1,n-1}=\sum_{i=0}^{n-1}a_{i,i}$$

In [9]:
def trazaIngenua(matriz):
    traza = 0
    #recorremos renglones
    for i in range (len(matriz)):
      #recorremos columnas
      for j in range (len(matriz[0])):
        if i == j:
          traza += matriz[i][j]
    return traza

def trazaMatriz(matriz):
    traza = 0
    #dado que los indices en la diagonal son iguales
    for i in range (len(matriz)):
      traza += matriz[i][i]
    return traza

a = creaMatriz(3)

print(trazaIngenua(a))
print(trazaMatriz(a))

3.0
3.0


#### Orden de Complejidad

Siendo estrictos podemos afirmar que el orden de complejidad al que pertenece la función *trazaIngenua* es al orden cuadratico $O(n^{2})$ ya que se recorren todos los indices de la matriz (no solo los elementos en la diagonal).

Sin embargo el orden de complejidad al que pertenece la función *trazaMatriz* es al orden lineal $O(n)$ ya que no realiza operaciones que no son necesarias y solo toma en cuenta los elementos en la diagonal principal de la matriz.

Por lo tanto podemos afirmar que **la función *trazaMatriz* tiene un menor costo en terminos computacionales por lo tanto es mejor en cuanto a desempeño** que *trazaIngenua*.

### Suma de matrices

Sea $A,B\in M_{n\times n}$ sobre $\mathbb{R}$ la suma de $A$ y $B$ se define como sigue.

$$\begin{equation} C=A+B =
\begin{pmatrix}
a_{00}+b_{00} & a_{01}+b_{01} & \cdots & a_{0n-1}+b_{0n-1}\\
a_{10}+b_{10} & a_{11}+b_{11} & \cdots & a_{1n-1}+ b_{1n-1}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n-10}+b_{n-10} & a_{n-11}+b_{n-11} & \cdots & a_{n-1n-1}+b_{n-1n-1}
\end{pmatrix}
\end{equation}$$

In [10]:
def sumaMatriz(m1, m2):
    #se crea la matriz resultante
    res = np.zeros_like(m1)
    #par de for's que sirven para recorrer ambas matrices
    for i in range(len(m1)):
      for j in range(len(m1[0])):
        #se asigna a res en la entrada adecuada el valor de la suma
        res[i][j] = m1[i][j] + m2[i][j]
    return res

#creamos 2 matriz de 3x3 con unos en sus entradas
a = creaMatriz(3)
b = creaMatriz(3)

#sumamos e imprimimos ambas matrices
print(sumaMatriz(a,b))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### Orden de Complejidad

Para realizar la suma de ambas matrices es necesario recorrer cada entrada de ambas matrices.

Es decir que por cada renglón (de tamaño $n$), se tiene que recorrer cada columna (también de tamaño $n$), de tal manera que despues de realizar la suma de $A$ y $B$ se habrán realizado $n \times n = n^{2}$ operaciones. Por lo que este algoritmo pertenece al orden cuadratico es decir $sumaMatriz \in O(n^{2})$.

En realidad por cada suma que realizamos para las entradas de la matriz $C$ se realiza mas de una operación, **se realiza una asignación (=), una suma (+) y 3 accesos a las localidad de las matrices**. Por lo que en realidad se realizan más de $n \times n = n^{2}$ operaciones, pero dada la definición de cota superior asintótica podemos desplazar la función cuadratica para acotar superiormente este algoritmo.

### Multiplicación de matrices.

Sea $A,B\in M_{n\times n}$ sobre $\mathbb{R}$ la multiplicación de $A$ y $B$ se define como sigue.

$$Marco A*B=\left(\begin{array}{cccc}
a_{00} & a_{01} & \cdots & a_{0n-1}\\
a_{10} & a_{11} & \cdots & a_{1n-1}\\
\vdots & \ddots & \ddots & \vdots\\
a_{n-10} & \cdots & \cdots & a_{n-1n-1}
\end{array}\right)*\left(\begin{array}{cccc}
b_{00} & b_{01} & \cdots & b_{0n-1}\\
b_{10} & b_{11} & \cdots & b_{1n-1}\\
\vdots & \ddots & \ddots & \vdots\\
b_{n-10} & \cdots & \cdots & b_{n-1n-1}
\end{array}\right)=\left(\begin{array}{cccc}
a_{00}b_{00}+\cdots+a_{0n-1}b_{n-10} & \cdots & \cdots & a_{00}b_{0n-1}+\cdots+a_{0n-1}b_{n-1n-1}\\
\vdots & \cdots & \cdots & \vdots\\
\vdots & \ddots & \ddots & \vdots\\
a_{n-10}b_{00}+\cdots+a_{n-1n-1}b_{n-10} & \cdots & \cdots & a_{n-10}b_{0n-1}+\cdots+a_{n-1n-1}b_{n-1n-1}
\end{array}\right)$$

De manera mas compacta podemos describir a las entradas de $C$ asi.

$$\begin{equation}
C_{ij} = \sum_{k=0}^{n-1} (a_{ik}*b_{kj})\;\;\forall\,i,j=0,\ldots,n-1
\end{equation}$$ 

## Punto flotante normalizado sistema decimal.

Dicho de otra forma, el numero real $x$, si es diferente de cero, se puede representar en la forma decimal de punto flotante normalizada como.

$$x=\pm r\times10^{n}\,\,\,\,\,\,(\frac{1}{10}\leq r<1)$$

Esta representación consta de tres partes:

• Un signo, ya sea $+$ ó $-$.

• Un número $r$ en el intervalo $[\frac{1}{10},1)$. A este valor se le conoce como **mantisa normalizada**.

• Una potencia entera de 10, es decir el exponente $n$.

## Punto flotante normalizado sistema binario. 

La representación de punto flotante en el sistema binario es similar a la del sistema decimal en diferentes aspectos.

 <font color="Teal" face="Comic Sans MS,arial">
  <h5 align="Left"><i>Hecho. Representación punto flotante normalizada base 2.</i></h5>
  </font>
  
Si $x\neq0$ se puede escribir como

$$x=\pm q\times2^{m}\,\,\,\,\,\,\,(\frac{1}{2}\leq q<1)$$

La mantisa $q$ se podría expresar como una sucesión de ceros o unos en el formato $q=(0.b_{1}b_{2}b_{3}....)_{2}$. Donde $b_{1}\neq0$. Por lo tanto $b_{1}=1$ y entonces necesariamente $q\geq\frac{1}{2}$. Por lo que $q$ al igual que $r$ esta acotado por el intervalo $[\frac{1}{2},1)$.

## Aspectos a considerar

Como todos sabemos, los valores reales son ilimitados (tanto en magnitudes grandes como en pequeñas), es por eso que al emplear una computadora para ejecutar algoritmos numéricos debemos tomar en cuenta ciertas consideraciones.


### Memoria limitada

Consideremos el siguiente ejemplo:

$\color{green}{Ejemplo}$. 

$$0.1_{10}=0.000110011..._{2}$$

La memoria de las computadoras es limitada y por lo tanto no se puede representar valores numéricos con precisión infinita.

No importa si se usan fracciones binarias o decimales, puede suceder que el numero no tenga una representación exacta, por lo tanto el valor a representar se tiene que truncar, pero:

• ¿Cuánta precisión se necesita?.

• ¿Dónde se necesita?.

• ¿Cuántos dígitos enteros y cuántos fraccionarios?.

## Tarea

<font color="Teal" face="Comic Sans MS,arial">
  <h3 align="Left"><i>Ejercicios.</i></h3>
  </font>
  
*  Estándar 1: Supongamos que se cuenta con una Longitud de Palabra de 5 bits en el sistema decimal. Los valores que se pueden representar no están normalizados y la totalidad de los bits se emplea para representar la parte entera.

– ¿Cuantos valores se pueden representar?.

– ¿Cuál es el valor más cercano a cero, diferente de cero (tanto positivo como negativo, para el estándar 1 solo positivo)?. 

– ¿Cuál es el valor más lejano del cero (tanto positivo como negativo, para el estándar 1 solo positivo)?.

– ¿Cuál es la diferencia (distancia numérica) entre un valor y el siguiente que puede ser representado mediante este estándar?.


* Estándar 2: Modifica el estándar 1, de manera que ahora el bit mas significativo se use para representar el signo. Responde las mismas preguntas.


* Estándar 3: Modifica el estándar 2 y ahora emplea el segundo bit mas significativo para el exponente, ademas los valores deben estar normalizados. Responde las mismas preguntas.


* Estándar 4: Considerando la necesidad de representar valores muy pequeños o muy grandes, modifica el estándar 3, de tal manera que ahora un valor de cero a 3 representa un exponente negativo. Y valores de 5 en adelante representan exponentes positivos. A esto se le conoce como **DESPLAZAMIENTO**. Responde las mismas preguntas.

## Referencias

1. Riswan Butt: Numerical Analysys Using Matlab, Jones and Bartlett.
2. Ward Cheney, David Kincaid:  Métodos Numéricos y Computación, Cenage Learning.
3. http://www.lcc.uma.es/~villa/tn/tema02.pdf
4. material de apoyo moodle

