<a href="https://colab.research.google.com/github/jugernaut/Numerico2021/blob/master/00_Introduccion/03_CCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Complejidad, Convergencia y Crecimiento del error.</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C. Miguel Angel Pérez León.</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón.</i></h5>
  <h5 align="center"><i>Materia: Análisis Numérico.</i></h5>
  </font>

## Introducción 

En presentaciones pasadas sentamos las bases de lo que es el análisis numérico. Y se mostraron algunas definiciones que sirven para realizar el análisis de un algoritmo.

Podemos pensar en estas definiciones como las herramientas de un médico que quiere examinar a un paciente, en este caso un algoritmo.

Dichas herramientas son:

1.   Complejidad Computacional (cota superior asintótica).
2.   Crecimiento del Error.
3.   Rapidez de Convergencia.

Para mostrar de manera práctica como emplear estas herramientas vamos a ver un par de ejemplos y de como llevar a cabo el análisis de dichos algoritmos.

## Matrices

Es bien conocido que las matrices son un elemento fundamental en el contexto matemático y por lo tanto es de vital importancia analizar los algoritmos que modelan el funcionamiento teórico de estos elementos.

Por otra parte los algoritmos asociados a las operaciones en el subespacio de las matrices son candidatos ideales para realizar su análisis.

Para simplificar un poco los ejemplos, vamos a restringir un poco el alcance de estos algoritmos al subespacio de las matrices cuadradas sobre el campo de los reales, es decir $A\in M_{n\times n}$ sobre $\mathbb{R}$. Sin embargo muchos de estos algoritmos se pueden extender al subespacio de las matrices de $m \times n$ incluso en el campo de los números complejos.


### Creación de una matriz

Para facilitar la definición de nuestros algoritmos vamos a usar la paquetería *numpy* de python, esta paquetería es la encargada de facilitar muchos de los cálculos que realizaremos en el curso.

Sin embargo, podemos pensar que una matriz es una lista de listas (viéndolo desde el punto de vista de la computación) o incluso un vector de vectores.

In [5]:
import numpy as np

#crea una matriz de tam x tam con unos y la imprime    
def creaMatriz(tam):
    #crea una matriz de tam x tam
    a = np.ones((tam,tam))
    #se devuelve la matriz 
    return a

# se imprime la matriz
print(creaMatriz(4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0, 1], [2, 3]]
[[0 1]
 [2 3]]
[0 1]
[2 3]
0
3


Este algoritmo unicamente sirve para generar una matriz de tamaño $n \times n$ en la que todas sus entradas tienen el valor 1, es decir.

$$A=\left(\begin{array}{ccc}
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1\\
1 & 1 & 1 & 1
\end{array}\right)$$

A partir de este punto podemos acceder a los elementos de la matriz mediante la notación *a[i][j]* donde i,j pertenecen a los indices de los renglones y las columnas respectivamente $a_{i,j}\;\forall\,i,j=0,\ldots,n-1$

### Traza de una matriz

El cálculo de la traza de una matriz es una de las operaciones mas sencillas de realizar, siempre y cuando se realice de manera correcta y se define como la suma de los elementos en la diagonal de la matriz.

Sea $A\in M_{n\times n}$ sobre $\mathbb{R}$ la traza de A se define como sigue.

$$traza(A)=a_{0,0}+a_{1,1}+\cdots a_{n-1,n-1}=\sum_{i=0}^{n-1}a_{i,i}$$

In [6]:
def trazaIngenua(matriz):
    traza = 0
    #recorremos renglones
    for i in range (len(matriz)):
      #recorremos columnas
      for j in range (len(matriz[0])):
        if i == j:
          traza += matriz[i][j]
    return traza

def trazaMatriz(matriz):
    traza = 0
    #dado que los indices en la diagonal son iguales
    for i in range (len(matriz)):
      traza += matriz[i][i]
    return traza

a = creaMatriz(3)

print(trazaIngenua(a))
print(trazaMatriz(a))

3.0
3.0


#### Orden de Complejidad

Siendo estrictos podemos afirmar que el orden de complejidad al que pertenece la función *trazaIngenua* es al orden cuadrático $O(n^{2})$ ya que se recorren todos los indices de la matriz (no solo los elementos en la diagonal).

Sin embargo el orden de complejidad al que pertenece la función *trazaMatriz* es al orden lineal $O(n)$ ya que no realiza operaciones que no son necesarias y solo toma en cuenta los elementos en la diagonal principal de la matriz.

Por lo tanto podemos afirmar que **la función *trazaMatriz* tiene un menor costo en términos computacionales por lo tanto es mejor en cuanto a desempeño** que *trazaIngenua*.

### Suma de matrices

Sea $A,B\in M_{n\times n}$ sobre $\mathbb{R}$ la suma de $A$ y $B$ se define como sigue.

$$\begin{equation} C=A+B =
\begin{pmatrix}
a_{0,0}+b_{0,0} & a_{0,1}+b_{0,1} & \cdots & a_{0,n-1}+b_{0,n-1}\\
a_{1,0}+b_{1,0} & a_{1,1}+b_{1,1} & \cdots & a_{1,n-1}+ b_{1,n-1}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n-1,0}+b_{n-1,0} & a_{n-1,1}+b_{n-1,1} & \cdots & a_{n-1,n-1}+b_{n-1,n-1}
\end{pmatrix}
\end{equation}$$

In [7]:
def sumaMatriz(m1, m2):
    #se crea la matriz resultante
    res = np.zeros_like(m1)
    #par de for's que sirven para recorrer ambas matrices
    for i in range(len(m1)):
      for j in range(len(m1[0])):
        #se asigna a res en la entrada adecuada el valor de la suma
        res[i][j] = m1[i][j] + m2[i][j]
    return res

#creamos 2 matriz de 3x3 con unos en sus entradas
a = creaMatriz(3)
b = creaMatriz(3)

#sumamos e imprimimos ambas matrices
print(sumaMatriz(a,b))

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


#### Orden de Complejidad

Para realizar la suma de ambas matrices es necesario recorrer cada entrada de ambas matrices.

Es decir que por cada renglón (de tamaño $n$), se tiene que recorrer cada columna (también de tamaño $n$), de tal manera que después de realizar la suma de $A$ y $B$ se habrán realizado $n \times n = n^{2}$ operaciones. Por lo que este algoritmo pertenece al orden cuadrático es decir $sumaMatriz \in O(n^{2})$.

En realidad por cada suma que realizamos para las entradas de la matriz $C$ se realiza más de una operación, **se realiza una asignación (=), una suma (+) y 3 accesos a las localidad de las matrices, es decir 5 operaciones por cada entrada de $C$**. Por lo que en realidad se realizan más de $n \times n = 5n^{2}$ operaciones, pero dada la definición de cota superior asintótica podemos desplazar la función cuadrática para acotar superiormente este algoritmo, es decir que dada la definición de cota superior, podemos ver que $c=5$ y $g(x)=n^{2}$.

### Multiplicación de matrices

Sea $A,B\in M_{n\times n}$ sobre $\mathbb{R}$ la multiplicación de $A$ y $B$ se define como sigue.

$$A*B=\left(\begin{array}{cccc}
a_{0,0} & a_{0,1} & \cdots & a_{0,n-1}\\
a_{1,0} & a_{1,1} & \cdots & a_{1,n-1}\\
\vdots & \ddots & \ddots & \vdots\\
a_{n-1,0} & \cdots & \cdots & a_{n-1,n-1}
\end{array}\right)*\left(\begin{array}{cccc}
b_{0,0} & b_{0,1} & \cdots & b_{0,n-1}\\
b_{1,0} & b_{1,1} & \cdots & b_{1,n-1}\\
\vdots & \ddots & \ddots & \vdots\\
b_{n-1,0} & \cdots & \cdots & b_{n-1,n-1}
\end{array}\right)=\left(\begin{array}{cccc}
a_{0,0}b_{0,0}+\cdots+a_{0,n-1}b_{n-1,0} & \cdots & \cdots & a_{0,0}b_{0,n-1}+\cdots+a_{0,n-1}b_{n-1,n-1}\\
\vdots & \ddots & \ddots & \vdots\\
\vdots & \ddots & \ddots & \vdots\\
a_{n-1,0}b_{0,0}+\cdots+a_{n-1,n-1}b_{n-1,0} & \cdots & \cdots & a_{n-1,0}b_{0,n-1}+\cdots+a_{n-1,n-1}b_{n-1,n-1}
\end{array}\right)$$

De manera compacta podemos describir a las entradas de $C$ asi.

$$\begin{equation}
C_{i,j} = \sum_{k=0}^{n-1} (a_{i,k}*b_{k,j})\;\;\forall\,i,j=0,\ldots,n-1
\end{equation}$$ 

In [8]:
#Multiplicacion de matrices
#se debe devolver m1*m2 con
#m1 y m2 matrices de dimensiones adecuadas
def multMatriz(m1,m2):
    resultado = np.zeros((len(m1), len(m2[0])))
    for i in range(len(m1)):
      for j in range(len(m2[0])):
        for k in range(len(m1)):
          resultado[i][j] += m1[i][k]*m2[k][j]
    return resultado

#se definen ambas matrices
a = np.array([[1,2],[3,4]])
b = np.array([[2,2],[2,2]])
#se muestran ambas matrices
print(a)
print(b)
#se imprime la multiplicacion
print(multMatriz(a,b))

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]
[[ 6.  6.]
 [14. 14.]]


#### Orden de Complejidad

Para realizar la multiplicación de ambas matrices es necesario recorrer cada entrada de ambas matrices y por cada entrada realizar una serie de sumas.

Este algoritmo requiere de 3 ciclos for anidados (uno dentro del otro) por lo que el numero de operaciones realizado es $n \times n \times n = n^{3}$ operaciones. Por lo que este algoritmo pertenece al orden cúbico es decir $multMatriz \in O(n^{3})$.

Para conocer con mayor exactitud el tiempo que le tomaría a este o cualquier algoritmo devolver un resultado sería necesario conocer el **set de instrucciones del microprocesador** donde se ejecute el algoritmo, ya que es la única manera certera de saber cuanto toma cada instrucción o FLOP.

### Determinante de una matriz

Sea $A \in M_{n\times n}$ sobre $\mathbb{R}$ el determinante de $A$ se define como sigue.

$$det(A)=\begin{cases}
a_{0,0}*a_{1,1}-a_{0,1}*a_{1,0} & n=2\\
\sum_{i=0}^{n-1}\left(-1\right)^{i}*a_{0,i}*det\left(subMatriz_{0,i}\left(A\right)\right) & n\geq2
\end{cases}$$

Donde la función $subMatriz_{0,i}\left(A\right)$ elimina el renglón cero y la columna $i$ de la matriz $A$.

#### Ejemplo de 3x3

$$A=\left(\begin{array}{ccc}
4 & 3 & 1\\
7 & 5 & -1\\
4 & 9 & 5
\end{array}\right)$$

$det(A)=\left(-1\right)^{0}\left(4\right)\left(det\left(\left(\begin{array}{cc}
5 & -1\\
9 & 5
\end{array}\right)\right)\right)\left(-1\right)^{1}\left(3\right)\left(det\left(\left(\begin{array}{cc}
7 & -1\\
4 & 5
\end{array}\right)\right)\right)\left(-1\right)^{2}\left(1\right)\left(det\left(\left(\begin{array}{cc}
7 & 5\\
4 & 9
\end{array}\right)\right)\right)$


In [ ]:
#Funcion auxiliar para eliminar un renglon y una columna
def subMatriz(mat, ren, col):
    copia = np.copy(mat)
    copia = np.delete(copia, (ren), axis=0)
    copia = np.delete(copia, (col), axis=1)
    return copia

# Determinante
# devuelve el determinante de la matriz m1
# se asume que m1 es cuadrada
def det(m1):
    if len(m1) == 2:
      return m1[0][0]*m1[1][1]-(m1[0][1]*m1[1][0])
    else:
      determinante = 0.0
      for i in range(len(m1[0])):
        determinante += ((-1)**i)*(m1[0][i])*det(subMatriz(m1,0,i))
    return determinante

a = np.array([[4,3,1],[7,5,-1],[4,9,5]])
#se muestran ambas matrices
print(a)
#se imprime la multiplicacion
print(det(a))

[[ 4  3  1]
 [ 7  5 -1]
 [ 4  9  5]]
62.0


#### Orden de Complejidad

Como se puede notar la definición de este algoritmo es **recursivo**, lo cual nos ayuda a **escribir menos código, a un gran costo de memoria**, sin embargo esta definición compacta nos ayuda a determinar de manera más sencilla el orden de complejidad al que pertenece este algoritmo y por qué el cálculo del determinante es algo muy costoso en cuanto a recursos se refiere.

Para calcular el determinante de una matriz de $n \times n$ necesitamos calcular $n$ determinantes de $n-1 \times n-1$ y por cada determinante de $n-1 \times n-1$ necesitamos calcular $n-1$ determinante de $n-2 \times n-2$, así hasta llegar al cálculo del determinante de una matriz de $2 \times 2$. De tal manera que al final se calcularon $n \times n-1\times n-2 \cdots 2 = !n$ determinantes. Por lo que podemos concluir que $det(A) \in O(n!)$.

Dado que ya conocemos los ordenes de complejidad computacional más comunes, poder afirmar que esta forma de calcular **el determinante de una matriz es extremadamente costo** y eso que solo hemos considerado el tiempo (número de operaciones o FLOP's) aun nos **falta considerar el espacio (memoria) en lo que también es extremadamente costoso**.

## Algoritmo de Horner

Cuando expresamos un valor numérico en el sistema decimal, de manera implícita estamos empleando potencias de base 10 para expresar dicho valor.

Para expresar un valor en el sistema decimal usamos una cadena de dígitos $(0,1,2,3,4,5,6,7,8,9)$, es decir.

$$valor-num\acute{e}rico=d_{n}d_{n-1}\ldots d_{1}d_{0}=d_{n}\times10^{n}+d_{n-1}\times10^{n-1}+\cdots d_{1}\times10^{1}+d_{0}\times10^{0}$$

Donde cada $d_{i} \in (0,1,2,3,4,5,6,7,8,9)$ y cada $d_{i}$ se multiplica por la base 10 elevada a la potencia positiva de la posición de $d_{i}$ y despueś del punto decimal el exponente ya es negativo. Vale la pena notar que esta forma de representar un valor numérico es muy parecido a la evaluación de un **polinomio de grado $n$**.

### Ejemplo

$$123=1\times10^{2}+2\times10^{1}+3\times10^{0}=100+20+3$$
$$P(x)=1\times x^{2}+2\times x^{1}+3\times x^{0}\quad P(10)=100+20+3$$

### Crecimiento del error 

De momento asumiremos que en cada operación aritmética que se realice vamos a **acarrear un error** (posteriormente veremos a que se debe), por lo tanto es de suma importancia realizar el menor número de operaciones posibles.

En el ejemplo anterior se realizan 3 sumas, 3 multiplicaciones y 3 potencias de base 10. En el caso de un valor con $n-digitos$ se realizarían $n$ sumas, $n$ multiplicaciones y $n$ potencias de base 10. Pero la pregunta sería, **¿existe una forma de llegar al mismo resultado con un número menor de operaciones?**.

¿Qué sucede si reescribimos este valor de la siguiente manera?.

$$1\times10^{2}+2\times10^{1}+3\times10^{0}=3+10\left(2+10\left(1\right)\right)=123$$

Resulta que obtenemos el mismo resultado pero se realizaron únicamente 2 sumas y 2 multiplicaciones. Es decir que logramos **reducir el numero total de operaciones**, por lo que también se **disminuye el error asociado a este algoritmo**.

### Generalización

De manera general podemos pensar en el algoritmo de Horner para un valor con $n-dígitos$ de la siguiente manera.

$$d_{n}b^{n}+d_{n-1}b^{n-1}+\cdots d_{1}b^{1}+d_{0}b^{0}=d_{0}+b(d_{1}+b(d_{2}+\cdots+b\underset{c_{n-2}}{\underbrace{(d_{n-2}+b\overset{c_{n-1}}{\overbrace{(d_{n-1}+bd_{n}})}})}\cdots))$$

Donde $d_i$ es el dígito en la posición $i$ y $b$ es la base del sistema numérico en el que se quiera expresar el valor numérico. Y el cálculo de los coeficientes $c_i$ se realiza de la siguiente manera.

$$c_{n}=d_{n},\quad c_{i}=bc_{i+1}+d_{i},\quad i=n-1,n-2,\ldots,0$$

Y así como esta expresión sirve para realizar menos operaciones para obtener el valor numérico de alguna expresión matemática, también sirve para la **evaluación de cualquier polinomio de grado $n$**.

### Análisis del algoritmo de Horner

Empleando el agoritmo de Horner para obtener el valor numérico de alguna expresión matemática o para evaluar un polinomio en un punto dado, se realizan menos operaciones.

Para un valor numérico con $n-dígitos$ o un polinomio de grado $n$ al emplear al algoritmo de Horner se realizan a lo más **$n-1$ sumas y $n-1$ multiplicaciones** es decir, $n-1+n-1=2(n-1)$.

Con lo que se **reduce en gran medida el crecimiento del error** y la **complejidad del algoritmo se mantiene en el orden lineal**, es decir $algoritmoHorner \in O(n)$.

### Ejemplo con un polinomio

Supongamos que tenemos el siguiente polinomio.

$$P\left(x\right)=d_{4}x^{4}+d_{3}x^{3}+d_{2}x^{2}+d_{1}x^{1}+d_{0}x^{0}=\left(1\right)x^{4}+\left(-4\right)x^{3}+\left(7\right)x^{2}+\left(-5\right)x^{1}+\left(-2\right)x^{0}$$

Y queremos evaluar este polinomio en $x=2$, es decir.

$$P\left(x\right)=\left(1\right)2^{4}+\left(-4\right)2^{3}+\left(7\right)2^{2}+\left(-5\right)2^{1}+\left(-2\right)2^{0}$$

Empleando el algoritmo de Horner reescribimos $P(x)$ como sigue.

$$P\left(2\right)=\left(-2\right)+2\left(\left(-5\right)+2\left(\left(7\right)+2\left(\left(-4\right)+2\left(1\right)\right)\right)\right)=0$$

Con lo que podemos afirmar que $x=2$ es una raíz de $P(x)$.



In [11]:
'''Algoritmo de Horner para evaluar polinomios
coef: lista de coeficientes comenzando de izquierda
a derecha por el de mayor grado
x: valor en el cual se quiere evaluar el polinomio
'''
def horner(coef, x):
    # el primer valor es igual al coeficiente mas grande
    p = coef[0]
    # comenzamos en 1 ya que el primer coeficiente se asigna antes
    # de ingresar al ciclo for
    for i in range(1,len(coef)):
        # se calcula el resto de los valores como se describe en
        # en algoritmo
        p = coef[i]+x*p
    print(p)

#se evalua el polinio (en forma de lista de coeficientes) en x=2
horner([1,-4,7,-5,-2], 2)

0


## Algoritmo Babilónico

Otro algoritmo usado desde hace mucho tiempo, es el algoritmo conocido como el método babilónico para la aproximación de la raíz cuadrada de un número.

Como lo indica su nombre este algoritmo era empleado desde los tiempos babilónicos.

La interpretación geométrica de este algoritmo es que dados dos valores iniciales $b$ y $a$ (base y altura) tratemos de construir un rectángulo cuya área sea el valor al cuadrado de la raíz cuadrada que estamos buscando.

### Pseudocódigo

En forma de pseudocódigo, este algoritmo luce de la siguiente forma:

1.   Tomemos dos valores $b$ y $a$ tales que $ba\approx x$ 
2.   Si $a\approx b$ vaya al paso 6, si no, vaya al paso 3
3.   Asigne $b\leftarrow\frac{a+b}{2}$
4.   Asigne $a\leftarrow\frac{x}{b}$
5.   Volver al paso 2
6.   Escribir $\sqrt{x}\approx b$

De manera más elegante podemos expresar este algoritmo como una función recursiva.

$$f_{n}\left(x\right)=\begin{cases}
x & n=0\\
\frac{1}{2}\left(\frac{x}{f_{n-1}\left(x\right)}+f_{n-1}\left(x\right)\right) & n\geq1
\end{cases}$$

Esta función genera una sucesión de aproximaciones de la raíz cuadrada de $x$, y podemos pensar que si $f_{\infty}\left(x\right)=\sqrt{x}$, es decir que realizamos suficientes iteraciones o **si la sucesión $\left\{ f\left(x\right)\right\} $ tiene suficientes elementos entonces la aproximación toma el valor exacto de la raíz cuadrada de $x$**.

In [ ]:
# Algoritmo para aproximar la raiz cuadrada de x
def babilonia(x):
    b = x
    a = 1
    # tolerancia del error en la aproximacion
    e = 0.00001
    while(b-a >= e):
        # se muestran los valores de la sucesion
        print(b)
        b = (a+b)/2
        a = x/b
    return b

# calculamos la raiz cuadrada de 16
print(babilonia(64))

64
32.5
17.234615384615385
10.474036101145005
8.292191785986859
8.005147977880979
8.000001655289593


### Convergencia

Dado que la finalidad del expresión $f_{n}\left(x\right)$ lo que busca es encontrar la aproximación de $\sqrt{x}$ en el intervalo $(a,b)$, podemos asumir que la raíz exacta $f_{\infty}\left(x\right)$ se encontrara en el intervalo $b_{n}-a_{n}=\frac{\left(b-a\right)}{2^{n-1}}$ es decir que después de haber dividido el intervalo inicial suficientes veces, nos aproximaremos tanto como deseamos a $\sqrt{x}$.



## Referencias

1. Riswan Butt: Numerical Analysys Using Matlab, Jones and Bartlett.
2. Ward Cheney, David Kincaid:  Métodos Numéricos y Computación, Cenage Learning.
3. Material de apoyo moodle
4. http://www.lcc.uma.es/~villa/tn/tema02.pdf
5. https://www.researchgate.net/profile/Thomas_Osler/publication/237415858_EXTENDING_THE_BABYLONIAN_ALGORITHM/links/5662a1c708ae4931cd5e5673/EXTENDING-THE-BABYLONIAN-ALGORITHM.pdf

