<a href="https://colab.research.google.com/github/jugernaut/Numerico2021/blob/master/Factorizaciones/FactorizacionLU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Factorización A=LU
### Proyecto PAPIME PE101019
- Autor: Miguel Angel Pérez León
- Rev: mar jun  24 17:08:27 CDT 2020

A lo largo del curso se ha mostrado el por que es importante encontrar la forma de resolver un sistema del tipo $A\vec{x}=\vec{b}$.

Incluso se ha mencionado en diferentes ocasiones que el calculo de la matriz $A^{-1}$ es demasiado costoso.

Es por este motivo que para evadir el calculo de $A^{-1}$ se emplean alternativas como buscar la forma triangular superior de A para después emplear substitución hacia atrás.

Sin embargo no siempre se puede garantizar que este algoritmo sea eficiente, por otro lado siempre podemos garantizar que la matriz $A$ puede ser descompuesta (factorizada) en el producto de dos matrices $LU$.

##Teorema

Sea $A\in M_{n\times n}$ una matriz **no singular**, se puede factorizar esta matriz en el producto de 2 matrices (únicas), una triangular inferior y otra triangular superior, es decir.

$$A=LU$$

En caso de que A sea singular, **la unicidad de L y U no esta garantizada**.

Una vez que se tienen las matrices $L$ y $U$ resolver el sistema $A\vec{x}=\vec{b}$ se reduce a resolver dos sistemas, uno triangular inferior y posteriormente uno triangular superior.

Las letras $L$ y $U$ hacen referencia a que son matrices tinagulares, una inferior $L$ (es decir que todos los valores arriba de la diagonal principal son cero) y otra superior $U$ (es decir que todos los valores debajo de la diagonal principal son cero).

## $A\vec{x}=LU\vec{x}$

Ya que se tienen ambas matrices $\left(LU\right)$ podemos substituirlas en el sistema original, de tal manera que ahora el sistema luce así.

$$A\vec{x}=LU\vec{x}=\vec{b}$$

Posteriormente podemos replantear la solución del sistema de la siguiente forma.

$$LU\vec{x}=\vec{b}\Longrightarrow L^{-1}LU\vec{x}=L^{-1}\vec{b}\Longrightarrow U\vec{x}=L^{-1}\vec{b}\tag{1}$$

De manera tal que ahora nos interesa primero encontrar una solución al sistema $L^{-1}\vec{b}=\vec{y}$, mismo que podemos reescribir.

$$L^{-1}\vec{b}=\vec{y}\Longrightarrow LL^{-1}\vec{b}=L\vec{y}\Longrightarrow\vec{b}=L\vec{y}\Longrightarrow L\vec{y}=\vec{b}\tag{2}$$

La ecuación (2) tiene la ventaja de ser un sistema triangular inferior, es por eso que la solución $\vec{y}$ puede ser calculada fácilmente empleando **substitución hacia adelante**. Y una vez calculada, podemos proceder a resolver el segundo sistema empleando **substitución hacia atras**.

$$U\vec{x}=\vec{y}\tag{3}$$

## Algoritmo para la factorización $LU$

La idea detrás del algoritmo consiste en llevar a la matriz A a su forma triangular superior $U$ mediante operaciones elementales y al mismo tiempo almacenar los factores multiplicativos que llevaron a la matriz $U$. Estos son multiplicados por -1 y almacenados en la matriz identidad que inicialmente es igual a $L$.

1.   Sean $A,U,L\in M_{n\times n}$, inicialmente las matrices $A$ y $U$ son iguales y $L$ es la identidad.
2.   Como se busca que $U$ sea una matriz triangular superior necesitamos generar ceros debajo de la diagonal.
3.   Supongamos que queremos generar un cero en la entrada $a_{\left(i,j\right)}$ $(j<i)$. Necesitamos multiplicar el renglón $r$ $(r<i)$ por un factor $f_{1}$ y sumarlo al renglón $i$.
4.   Al mismo tiempo es necesario substituir la entrada $l_{\left(i,j\right)}$ por $-f_{1}$. Es decir $l_{\left(i,j\right)}=-f_{1}$.
5.   Se repite, los pasos 3 y 4, hasta que la matriz $U$ alcanza su forma triangular superior.

## Ejemplo factorización $LU$

Sean 

$$A=\left(\begin{array}{ccc}
-4 & -3 & 1\\
8 & 11 & -1\\
4 & 18 & 5
\end{array}\right)=U\;y\;L=\left(\begin{array}{ccc}
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{array}\right)\Longrightarrow A=UL$$

Multipliquemos el renglón 1 de $A$ por **2** y lo sumamos al segundo renglón.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
4 & 18 & 5
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
{\color{blue}{-2}} & 1 & 0\\
0 & 0 & 1
\end{array}\right)$$

Ahora multiplicamos el renglón 1 por **1** y se suma al tercer renglón.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 15 & 6
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
{\color{blue}{-1}} & 0 & 1
\end{array}\right)$$

Finalmente se multiplica por **-3** el segundo renglón y se suma al tercero.

$$U=\left(\begin{array}{ccc}
-4 & -3 & 1\\
0 & 5 & 1\\
0 & 0 & 3
\end{array}\right)\quad L=\left(\begin{array}{ccc}
1 & 0 & 0\\
-2 & 1 & 0\\
-1 & {\color{blue}3} & 1
\end{array}\right)$$

## Comprobemos el resultado anterior en Python, es decir.

$$LU=A$$

In [ ]:
import numpy as np

L = np.array([[1,0,0],[-2,1,0],[-1,3,1]])
U = np.array([[-4,-3,1],[0,5,1],[0,0,3]])

print(np.matmul(L,U))

[[-4 -3  1]
 [ 8 11 -1]
 [ 4 18  5]]
