<a href="https://colab.research.google.com/github/jugernaut/Numerico2021/blob/desarrollo/03_SolucionSistemasLineales/05_Numero_condicion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font color="Teal" face="Comic Sans MS,arial">
  <h1 align="center"><i>Número de condición.</i></h1>
  </font>
  <font color="Black" face="Comic Sans MS,arial">
  <h5 align="center"><i>Profesor: M.en.C. Miguel Ángel Pérez León.</i></h5>
    <h5 align="center"><i>Ayudante: Jesús Iván Coss Calderón.</i></h5>
  <h5 align="center"><i>Materia: Análisis Numérico.</i></h5>
  </font>

# Introducción

Para este punto del curso ya debe ser claro que una de las principales características de cualquier solución (algoritmo) $\widehat{f}$ es la estabilidad

De tal manera que determinar que tan estable es esta solución es importante para el análisis numérico.

Recordando un poco la definición de estabilidad para matrices, tenemos. 



# Definición

Un algoritmo es estable para una clase de matrices $C$ si $\forall A\in C$, la solución computacional $\widehat{x}$ generada por el algoritmo es la solución exacta cercana a la solución del problema. Así que para el sistema lineal $Ax=b$, un algoritmo es estable si $\forall A\in C$ y para cada $b$, se produce una solución computacional $\widehat{x}$ que satisface $\left(A+E\right)\widehat{x}=b+\delta b$

Para alguna $E$ y $\delta b$, donde $\left(A+E\right)$ es cercana a $A$ y $b+\delta b$ es cercano a $b$.

# Condicionamiento

Un problema (con respecto a un conjunto de datos) es llamado 'mal condicionado', si una pequeña perturbación relativa en los datos iniciales, produce un error relativo grande en la solución computacional, sin importar el método de solución. Por otro lado, es llamado 'bien condicionado', si toda pequeña perturbación en los datos iniciales, produce pequeños errores relativos en la solución.

Sea $x$ e $y$ el dato original y el dato perturbado ligeramente y sea $f(x)$ y $f(y)$ sus respectivas soluciones. Se tiene lo siguiente

**Problema bien condicionado**: si $y$ es cercano a $x$ entonces $f(y)$ es cercano a $f(x)$.

**Problema mal condicionado**: aunque $y$ sea cercano a $x$ entonces $f(y)$ puede alejarse en gran medida de $f(x)$.


## Número de Condición

El numero de condición del problema $f$ con respecto al dato $x$ es definido como

$$\frac{Error\,relativo\,en\,la\,soluci\acute{o}n}{Perturbaci\acute{o}n\,relativa\,en\,el\,dato}=\frac{\frac{\left||f(x)-f(y)\right|}{\left||f(x)\right||}}{\frac{\left||x-y\right||}{\left||x\right||}}$$

Si $f:\mathbb{R}^{n}\longrightarrow\mathbb{R}^{m}$ y $x,y\in\mathbb{R}^{n}$, entonces el número de condición se define formalmente como

$$\underset{\epsilon_{M}\rightarrow0}{\limsup}\left\{ \frac{\frac{\left\Vert f(x)-f(y)\right\Vert }{\left\Vert f(x)\right\Vert }}{\frac{\left\Vert x-y\right\Vert }{\left\Vert x\right\Vert }}\quad tal\,que\quad\left\Vert x-y\right\Vert \leq\epsilon_{M}\right\} $$

Observación: Un problema es mal condicionado si el numero de condición es $\gg1$ (mucho mayor que 1).

## Ejemplo

El problema de encontrar raíces de un polinomio puede ser altamente mal condicionado. Considere resolver la ecuación 

$$f(x)=x^{2}-2x+1$$

Ahora perturbe el coeficiente 2 por 0.00001, es decir $$\widehat{f}(x)=x^{2}+2.00001x+1$$

y analice que sucede con las soluciones y sus respectivos errores relativos.

En general, si un algoritmo **estable hacia atrás** es aplicado a un problema con numero de condición $\kappa$, entonces la precisión de la solución dependerá de $\kappa$.

Si $\kappa$ es muy pequeño, el resultado sera preciso; en caso contrario la precisión no tiene garantía. Por lo que podemos decir que **la precisión depende del numero de condicionamiento** $\kappa$.

In [ ]:
# se clona el proyecto y se agrega a la sesion
!git clone https://github.com/jugernaut/Numerico2021.git
# importamos la biblioteca correspondiente gutils
import Numerico2021.Utils.gutils as vis

# f sin la perturbacion
def fsingorro(x):
  return (x*x)-2*x+1

# f con una diminuta perturbacion
def fcongorro(x):
  return (x*x)-2.00001*x+1

# evaluaciones de las respectivas funciones
fngorro = vis.newton(fsingorro, 0.0001, 100, -2)
fgorro = vis.newton(fcongorro, 0.0001, 100, -2)
# error relativo entre las f's
errorrel = abs(fgorro-fngorro)/abs(fngorro)

# se imprimen los resultados
print(fngorro)
print(fgorro)

# error relativo 'grande' aunque la perturbacion fue diminuta
print(errorrel)

fatal: destination path 'Numerico2021' already exists and is not an empty directory.
0.9999686826426051
0.9968430501939348
0.003125730338284381


# Análisis de la Perturbación sobre $x$ y $b$

Cuando un analista numérico se propone resolver un problema, normalmente los datos con los que trabaja no son los datos originales, si no con datos que han sido perturbados. La pregunta que surge naturalmente es:

¿De que manera afectaran estas perturbaciones a la solución?.

Una técnica teórica del análisis numérico que investiga estos cambios, la cual es independiente del algoritmo usado para resolver el problema, se llama **análisis de la perturbación**.

## Nomenclatura y efectos de las perturbaciones

Sea $A\in M_{n\times n}$ y $\vec{x}, \vec{b} \in  \mathbb{R}^{n}$. Supongamos que $\vec{x}$ y $\vec{b}$ han sido perturbados y que la matriz $A$ es exacta.

$$\begin{array}{c}
A\longrightarrow A\quad(sin\,cambios)\\
\vec{b}\longrightarrow \vec{b}+\vec{\delta b}\quad(\vec{\delta b}=perturbaci\acute{o}n\,en\,el\,vector\,b)\\
\vec{x}\longrightarrow \vec{x}+\vec{\delta x}\quad(\vec{\delta x}=cambio\,en\,la\,soluci\acute{o}n)
\end{array}$$

Nota: En lo subsiguiente, para mayor claridad se omite el simbolo $( \vec{} )$, en los respectivos vectores $\vec{x}, \vec{b}, \vec{\delta x}, \vec{\delta b}$, sin embargo siguen siendo vectores.

## Teorema (Cota del condicionamiento)

Si $\delta x$  y $\delta b$ son, respectivamente las perturbaciones de $x$ y $b$ en el sistema lineal $Ax=b$, con $A$ no singular y $b\neq \vec{0}$ , entonces 

$$\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }\geq\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }\geq \frac{\left\Vert \delta b\right\Vert }{\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \left\Vert b\right\Vert }$$

Como $Ax=b$ y $A\left(x+\delta x\right)=b+\delta b$, tenemos que 

$$
\begin{eqnarray*}
A\left(x+\delta x\right)&	=	& b+\delta b \\
Ax+A\delta x &=&	b+\delta b \\
b+A\delta x	&=&	b+\delta b\quad(ya\,que\,Ax=b) \\
A\delta x	&=&	\delta b \\
\Rightarrow	\delta x	&=& A^{-1}\delta b
\end{eqnarray*}
$$

Tomando cualquier norma matricial subordinada tenemos

$$\left\Vert \delta x\right\Vert \overset{\underbrace{prop\,5\,nor.}}{\leq} \left\Vert A^{-1}\right\Vert \left\Vert \delta b\right\Vert \tag{1}$$

De nuevo, tomando la misma norma y aplicando en ambos lados de $Ax=b$, se tiene $\left\Vert Ax\right\Vert =\left\Vert b\right\Vert$ ó

$$\left\Vert b\right\Vert =\left\Vert Ax\right\Vert \leq\left\Vert A\right\Vert \left\Vert x\right\Vert \Rightarrow\left\Vert b\right\Vert \leq\left\Vert A\right\Vert \left\Vert x\right\Vert \tag{2} $$

Ahora si combinamos (1) y (2), se obtiene

$$
\begin{eqnarray*}
\left\Vert \delta x\right\Vert \left\Vert b\right\Vert 	&\leq&\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \left\Vert x\right\Vert \left\Vert \delta b\right\Vert \\
\Rightarrow	\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert } &\leq&	\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }
\end{eqnarray*} \tag{3}
$$

Por otra parte $A\delta x=\delta b\Longrightarrow\left\Vert A\right\Vert \left\Vert \delta x\right\Vert \geq\left\Vert \delta b\right\Vert $ por lo tanto 

$$\left\Vert \delta x\right\Vert \geq\frac{\left\Vert \delta b\right\Vert }{\left\Vert A\right\Vert } \tag{4}$$

De igual manera de $Ax=b$, se tiene que 

$$ 
\begin{eqnarray*}
Ax &=& b\\
x &=& A^{-1}b\\
\left\Vert x\right\Vert &\leq &\left\Vert A^{-1}\right\Vert
\left\Vert b \right\Vert \\
\Rightarrow\frac{1}{\left\Vert x\right\Vert } &\geq&\frac{1}{\left\Vert A^{-1}\right\Vert \left\Vert b\right\Vert } \tag{5}
\end{eqnarray*}
$$

Combinando (4) y (5), tenemos

$$\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }\geq\frac{\left\Vert \delta b\right\Vert }{\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \left\Vert b\right\Vert }$$

Finalmente, si combinamos (3) y (5) podemos concluir que.

$$\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }\geq\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }\geq \frac{\left\Vert \delta b\right\Vert }{\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert \left\Vert b\right\Vert }$$

# Número de Condición

El número de condición nos proporciona información valiosa sobre la estabilidad de un algoritmo que en este caso es representado por una matriz.


## Definición

El número $\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert$  es llamado el número de condición de $A$ y es denotado por $\kappa\left(A\right)$ ó $ Cond\left(A\right) $

El teorema sobre la cota de condicionamiento muestra que un cambio relativo en la solución puede ser tan grande como $\kappa\left(A\right)$ multiplicado por el cambio relativo en el vector $b$. 

Lo que significa que **si $\kappa\left(A\right)$ no es demasiado grande**, entonces una pequeña perturbación en el vector $b$ **tendrá muy poco efecto sobre la solución**. 

Por otro lado **si $\kappa\left(A\right)$ es grande**, entonces incluso una pequeña perturbación en el vector $b$ **cambia drásticamente la solución**. 

## Ejemplo

Sean

$$A=\left(\begin{array}{ccc}
1 & 2 & 1\\
2 & 4.0001 & 2.002\\
1 & 2.002 & 2.004
\end{array}\right) \quad b=\left(\begin{array}{c}
4\\
8.0021\\
5.006
\end{array}\right)$$

Encuentre $x$ y después cambie $b$ por $b'=\left(\begin{array}{c}
4\\
8.0020\\
5.0061
\end{array}\right)$

La solución exacta es $x=\left(1,1,1\right)^{T}$. Veamos la perturbación relativa:

$$\frac{\left\Vert b'-b\right\Vert }{\left\Vert b\right\Vert }=\frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }=1.3795\times10^{-5}\qquad(muy\,peque\tilde{n}o)$$

Ahora, si resolvemos el sistema $Ax'=b'$, tenemos que 

$$x'=x+\delta x=\left(\begin{array}{c}
3.0850\\
-0.0436\\
1.0022
\end{array}\right)$$

$x'$ es completamente diferente a $x$. Ademas $\kappa\left(A\right)=322099.88$, lo cual corrobora el teorema.

Por otra parte el error relativo en la solución es $\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }=1.3461$ y se comprueba que la desigualdad de la cota de condicionamiento se cumple 

$$\kappa\left(A\right)\frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }=4.4433>1.3461=\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }$$

In [ ]:
# se define la matriz A
A = np.array([[1,2,1],[2,4.0001,2.002],[1,2.002,2.004]])
# vector b
b = np.array([4,8.0021,5.006])
# solucion del sistema
x = np.linalg.solve(A,b)
# veamos la solucion
print(x)

# ahora perturbemos un poco el vector b
b = np.array([4,8.0020,5.0061])
# nueva solucion del sistema
xprima = np.linalg.solve(A,b)
# veamos la solucion
print(xprima)

# numero de condicion de la matriz A
print(np.linalg.cond(A))

[1. 1. 1.]
[ 3.08495851 -0.04356846  1.00217842]
322099.88408211124


# Análsis de la perturbación en la matriz A

Supongamos que $A$ ha sido perturbada y que el vector $b$ es exacto 

$$\begin{array}{c}
A\longrightarrow A+\triangle A\quad(\triangle A=perturbaci\acute{o}\,en\,matriz\,A)\\
b\longrightarrow b\quad(sin\,cambios)\\
x\longrightarrow x+\delta x\quad(\delta x=cambio\,en\,la\,soluci\acute{o}n)
\end{array} $$

Suponga que $A$ es no singular y $b\neq0$. Si $\triangle A$  y $\delta x$ son respectivamente, las perturbaciones de $A$ y $x$ en el sistema lineal $Ax=b$. Suponer que $\triangle A$  es tal que $\left\Vert \triangle A\right\Vert <\frac{1}{\left\Vert A^{-1}\right\Vert }$. Entonces 

$$\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }\leq\frac{\kappa\left(A\right)\frac{\left\Vert \triangle A\right\Vert }{\left\Vert A\right\Vert }}{1-\kappa\left(A\right)\frac{\left\Vert \triangle A\right\Vert }{\left\Vert A\right\Vert }}$$

## Ejemplo

Sean

$$A=\left(\begin{array}{ccc}
1 & 2 & 1\\
2 & 4.0001 & 2.002\\
1 & 2.002 & 2.004
\end{array}\right) \quad b=\left(\begin{array}{c}
4\\
8.0021\\
5.006
\end{array}\right)$$


Encuentre $x$ y después cambie $a_{23}=2.002$ por $2.0021$

La solución exacta es $x=(1,1,1)^{T}$. Veamos la perturbación relativa:

$$\triangle A=+10^{-4}\left(\begin{array}{ccc}
0 & 0 & 0\\
0 & 0 & 0.1000\\
0 & 0 & 0
\end{array}\right)\quad(muy\,peque\tilde{n}o)$$

Sin embargo, al resolver el sistema $\left(A+\triangle A\right)x'=b$, tenemos que: 

$$x'=\left(\begin{array}{c}
3.0852\\
-0.0437\\
1.0021
\end{array}\right),\quad\delta x=x'-x=\left(\begin{array}{c}
2.0852\\
-1.0437\\
0.0021
\end{array}\right)$$

Error relativo $=\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }=1.3463$, lo cual es bastante grande.

Ademas 

$$\kappa\left(A\right)=\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert =322758.59$$

In [ ]:
# solucion del sistema
x = np.linalg.solve(A,b)
# veamos la solucion
print(x)

# cambiamos la entrada 2,3 perturbacion en la matriz
deltaA = np.array([[1,2,1],[2,4.0001,2.0021],[1,2.002,2.004]])
# solucion del sistema
nuevaSol = np.linalg.solve(deltaA,b)
# veamos la solucion
print(nuevaSol)

# deltax
print(nuevaSol-x)

# numero de condicion de la matriz perturbada
print(np.linalg.cond(deltaA))

[1. 1. 1.]
[ 3.08523909 -0.04365904  1.002079  ]
[ 2.08523909e+00 -1.04365904e+00  2.07900208e-03]
322758.5924078853


# Análisis de la perturbación en $A$ y $b$

Supongamos que $A$ ha sido perturbada y el vector $b$ también.

$$\begin{array}{c}
A\longrightarrow A+\triangle A\quad(\triangle A=perturbaci\acute{o}\,en\,matriz\,A)\\
b\longrightarrow b+\delta b\quad(\delta b=cambio\,en\,el\,vector\,b)\\
x\longrightarrow x+\delta x\quad(\delta x=cambio\,en\,la\,soluci\acute{o}n)
\end{array}$$

Suponga que $A$ es no singular y $b\neq0$, y $\left\Vert \triangle A\right\Vert <\frac{1}{\left\Vert A^{-1}\right\Vert }$. Entonces

$$\frac{\left\Vert \delta x\right\Vert }{\left\Vert x\right\Vert }\leq\left(\frac{\kappa\left(A\right)\frac{\left\Vert \triangle A\right\Vert }{\left\Vert A\right\Vert }}{1-\kappa\left(A\right)\frac{\left\Vert \triangle A\right\Vert }{\left\Vert A\right\Vert }}\right)\left(\frac{\left\Vert \triangle A\right\Vert }{\left\Vert A\right\Vert }+\frac{\left\Vert \delta b\right\Vert }{\left\Vert b\right\Vert }\right)$$

# Resumen

El numero de condición de una matriz $A\in M_{n\times n}$.

*   El numero de condición de una matriz $A\in M_{n\times n}$.
$$\kappa\left(A\right)=\left\Vert A\right\Vert \left\Vert A^{-1}\right\Vert$$

    Nos proporciona información importante sobre las caracteristicas de la matriz $A$.

*   Una vez que conocemos este valor, podemos determinar si nuestro problema está bien condicionado ó si por el contrario está mal condicionado.



#  Referencias

*   Riswan Butt, Numerical Analysys Using Matlab, Jones and Bartlett.
*   Ward Cheney, David Kincaid, Métodos Numéricos y Computación, Cenage Learning.
*   Richard L. Burden, J. Douglas Faires, Análisis Numérico, Math Learning.
*   Yuri N. Skiba, Introducción a los Métodos Numéricos.
*   Quarteroni, A, Sacco R., Numerical mathematics, Springer. 2007.

